### ISSUE TITLE
Objects are enqueued by Zipmaker before existing in the catalog

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/preservation_catalog#1120]
See: https://app.honeybadger.io/projects/54415/faults/39957333

in the logs:

```
# grep rb803rc6397 production.log
I, [2018-10-16T15:34:18.843973 #26075]  INFO -- : [4fad0d40-6593-4627-a14d-250701f0f371]   Parameters: {"checksums_validated"=>"true", "druid"=>"druid:rb803rc6397", "incoming_size"=>"12172869166", "incoming_version"=>"1", "storage_location"=>"/services-disk16"}
I, [2018-10-16T15:34:18.859761 #26075]  INFO -- : [4fad0d40-6593-4627-a14d-250701f0f371] [ActiveJob] Enqueued ZipmakerJob (Job ID: 7cd17784-cdab-4ded-a43c-70b18434572a) to Resque(zipmaker) with arguments: "rb803rc6397", 1
I, [2018-10-16T15:34:18.865379 #26075]  INFO -- : [4fad0d40-6593-4627-a14d-250701f0f371] create(rb803rc6397, services-disk16) added object to db as it did not exist

```

**Comment by atz** [comment]
That's not literally true, it's just the order of the log messages.  

`ZippedMoabVersion.replicate!` does:
```ruby
return nil unless persisted?
```
So the job would never get enqueued if the object wasn't already created.  Obviously, that makes sense since the method is typically called via `after_create` hook.  

That HoneyBadger error message is from `Moab::StorageServices`, which is about the **filesystem**:
```
Moab::ObjectNotFoundException: No storage object found for rb803rc6397
```

 `Moab` code has no knowledge of the database, so order of creation/checking doesn't seem like it could be a factor.  That error message is from `AuditResults::CREATED_NEW_OBJECT` in POH.  It looks like there is maybe a mismatch in the location based on leading slash.

**Comment by atz** [comment]
The job code was running without being re-initialized (w/ the new configured storage root).  This is the same problem we saw previously.  

There were 3 `resque-pool-master` processes on prod 04, for example.  There should only be 2.  One was a week old, so its workers didn't have your new configs, so Moab couldn't locate content there.  

The bigger problem is: resque-pool is not restarting cleanly on deploy.  A new pool is brought up, but the old processes are not killed.  This relates to `capistrano-resque-pool.rake` and the `resque:pool:stop` task.

**Comment by ndushay** [comment]
@jmartin-sul has thi happened in the last 4 years?  If not, please close the ticket.

**Comment by ndushay** [comment]
Closing this issue;  we are on sidekiq now so if this still occurs (questionable), sidekiq automated retries will take care of it.
