### ISSUE TITLE
New versions not correctly flowing to replicate / zip-maker

### ISSUE THREAD

**Issue by julianmorley** [sul-dlss/preservation_catalog#1124]
This appears to be load-related.

When PresCat processes a large number of new druid-versions, a small fraction of those druid-versions are not successfully replicated to endpoints.

For example, yesterday we added a little over 10,000 new druid-versions (all at version 1). Of those, 4 druid-versions *did not* get replicated to AWS. These versions have correct CompleteMoab and ZippedMoabVersion records, but no ZipPart records. This implies the replication request never made it to ZipMaker / resque.

I only discovered this because of my out-of-band monitoring and auditing of prescat. This is the second time in as many weeks that I've seen this - 10K+ new ingest, a handful of druids not getting replicated with no evidence of failure. Last time it was 6 druid-versions, all at v1, that didn't get detected and did not subsequently get caught by audit. Manually calling ZipMaker on those druid-versions resulted in successful replication and ZipPart records.

**Comment by julianmorley** [comment]
## Failed druid: 
Note it has a ZMV but no corresponding zip part.
```
[13] pry(main)> zmv = ZippedMoabVersion.by_druid('tr398br9994') 
=> [#<ZippedMoabVersion:0x000000001cc9ee30
  id: 8300535,
  version: 1,
  complete_moab_id: 1510328,
  zip_endpoint_id: 1,
  created_at: Tue, 06 Nov 2018 22:54:11 UTC +00:00,
  updated_at: Tue, 06 Nov 2018 22:54:11 UTC +00:00>]
[14] pry(main)> zp = ZipPart.find_by( zipped_moab_version_id: 8300535)
=> nil
```
## Same batch, but success
This druid-version was successfully replicated during the same session that the failure occurred in.
```
[8] pry(main)> zmv = ZippedMoabVersion.by_druid('zz978fx5681') 
=> [#<ZippedMoabVersion:0x000000001ce0cc40
  id: 8298089,
  version: 1,
  complete_moab_id: 1507924,
  zip_endpoint_id: 1,
  created_at: Tue, 06 Nov 2018 17:57:20 UTC +00:00,
  updated_at: Tue, 06 Nov 2018 17:57:20 UTC +00:00>]
[9] pry(main)> zp = ZipPart.find_by( zipped_moab_version_id: 8298089)
=> #<ZipPart:0x000000001cd6c1f0
 id: 8358330,
 size: 4657719,
 zipped_moab_version_id: 8298089,
 created_at: Tue, 06 Nov 2018 17:57:24 UTC +00:00,
 updated_at: Wed, 07 Nov 2018 08:12:26 UTC +00:00,
 md5: "2373667df36f956d3a3522af5b5f9e50",
 create_info:
  "{:zip_cmd=>\"zip -r0X -s 10g /sdr-transfers/zz/978/fx/5681/zz978fx5681.v0001.zip zz978fx5681/v0001\", :zip_version=>\"Zip 3.0 (July 5th 2008)\"}",
 parts_count: 1,
 suffix: ".zip",
 status: "ok",
 last_existence_check: Wed, 07 Nov 2018 08:12:26 UTC +00:00,
 last_checksum_validation: Wed, 07 Nov 2018 08:12:26 UTC +00:00>
```

**Comment by julianmorley** [comment]
My suspicion is that it's related to Redis connection timeout errors; for whatever reason, when a box is under load, some redis connections don't get through. If the connection was a request to replicate a druid to an endpoint, it doesn't happen.

**Comment by ndushay** [comment]
Is this still a problem, Julian?  If not, close???

**Comment by ndushay** [comment]
I suspect this might be fixed by switching to sidekiq, but :shrug:

**Comment by jmartin-sul** [comment]
i don't know, other than the occasional network or file read failure in zipping and delivery of archive content, that this is still an issue.  there are still a number of incomplete archives for druids, but dealing with those is captured in https://github.com/sul-dlss/preservation_catalog/issues/1733

if the initial problem was a result of a failed archive creation or delivery that never got retried, i'd agree that sidekiq would address the problem.  otherwise, it would seem to be an issue with job handoffs, which i don't think sidekiq would address.

either way, i'm going to close this for now, under the assumption that #1733 covers the remediation for known occurrences, and that we're not generating much in the way of new occurrences of this problem.  also, first-responders are generally more on top of timely retries now (and we have fewer failures to deal with since we've gotten ceph interactions to be more stable).
