### ISSUE TITLE
Get a list of all druids preservation-robots processed during prescat API redirection fail

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/preservation_catalog#1286]
This was approximately between 8:45am Monday and 12pm on Tuesday of this week.

Potential places to search for the information:
* preservation_robots logs (all VMs)
* search argo for all druids accessioned from Monday to Tuesday afternoon (possibly including some from Sunday): https://argo.stanford.edu/catalog?utf8=%E2%9C%93&all=true&f[accessioned_latest_dttsi][]=[2019-12-16T00%3A00%3A00.000Z+TO+2019-12-17T23%3A59%3A59.000Z]&commit=submit

**Comment by ndushay** [comment]
Druids with this message during the time period pres-robots couldn't talk to pres-cat:
```
"Item druid:wn974hy2564 is not queued, but has status of 'waiting'. Will skip processing"
```

- `wn974hy2564`
- `nr758rg7861`
- `ht780vn9046`

**Comment by ndushay** [comment]
Here is a file showing the 516 candidate druids from the preservation_robots logs.  Note that I was a bit generous with the times - these may include some druids that were processed after the problem was fixed.

[prod-druids-alpha.txt](https://github.com/sul-dlss/preservation_catalog/files/3985393/prod-druids-alpha.txt)

**Comment by ndushay** [comment]
I'm closing this;  I put the information from the above 2 comments into #1288
