### ISSUE TITLE
Remediate intersection of druids from 1286 and 1287

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/preservation_catalog#1288]
Get the intersection of druids listed in #1286 (robots) and #1287 (M2C) and fix preservation_catalog for all these objects as needed.

Blocked by ~~#1286~~ and #1287.

**Comment by ndushay** [comment]
FYI:

Julian found these objects had *more than one version* preserved since Monday (but not limited to the narrower time window):

```
qg503qz6786,1 <-- both of these versions during outage
qg503qz6786,2 <-- both of these versions during outage
dq523xp6340,1 <-- both of these versions during outage
dq523xp6340,2 <-- both of these versions during outage
hr944hd2875,1 . <--- before Monday
hr944hd2875,2
hs228pn0060,1  <--- before Monday
hs228pn0060,2
tb357ww9071,6 <-- both of these versions during outage
tb357ww9071,7 <-- both of these versions during outage
```

**Comment by ndushay** [comment]
Here is a file showing the 516 candidate druids from the preservation_robots logs.  Note that I was a bit generous with the times - these may include some druids that were processed after the problem was fixed.

[prod-druids-alpha.txt](https://github.com/sul-dlss/preservation_catalog/files/3985393/prod-druids-alpha.txt)

here are the raw log messages:

[prod-pres-robots-log-from-prescat-conn-outage.txt](https://github.com/sul-dlss/preservation_catalog/files/3985407/prod-pres-robots-log-from-prescat-conn-outage.txt)

**Comment by julianmorley** [comment]
ht780vn9046 - services-disk20, 2 versions, zips on all endpoints.
nr758rg7861 - services-disk21, 1 version, NOT REPLICATED.
vw518px3512 -  services-disk21, 1 version, NOT REPLICATED.
wn974hy2564 - services-disk15, 3 versions, zips on all endpoints.

**Comment by ndushay** [comment]
Here are the druids from the only M2C check results that *may* have meant that an object that went through pres-robots during the outage *could* have incorrect data in the prescat database:

from #1287

This led me to get the following info about invalid_checksum status objects in the prescat db:
- 513 total  invalid_checksum statuses for complete_moabs
    - 506 - services-disk02 [services-disk02-invalid-checksum-druids.txt](https://github.com/sul-dlss/preservation_catalog/files/3990265/services-disk02-invalid-checksum-druids.txt)
    - 1 - services-disk03: `fk847cz0044`
    - 1 - services-disk04: `gh926rx4162`
    - 3 - services-disk08: `"py880rz2144`, `mg599hw5271`, `vq518cf9512`
    - 1 - services-disk10:  `zx284xc2961`
    - 1 - services-disk16:  `fr360kt0172`

^^ so we need to take this full list of druids and find the intersection with [prod-druids-alpha.txt](https://github.com/sul-dlss/preservation_catalog/files/3985393/prod-druids-alpha.txt) (The druids that ran through preservation robots during outage)

**Comment by ndushay** [comment]
"Ok" means NOT processed by pres-robots during outage

Possibly problematic prescat entries after outage:
   - 506 - services-disk02 [services-disk02-invalid-checksum-druids.txt](https://github.com/sul-dlss/preservation_catalog/files/3990265/services-disk02-invalid-checksum-druids.txt)
    - 1 - services-disk03: `fk847cz0044` - OK!
    - 1 - services-disk04: `gh926rx4162` - OK!
    - 3 - services-disk08: `"py880rz2144`, `mg599hw5271`, `vq518cf9512` - all OK!
    - 1 - services-disk10:  `zx284xc2961` - OK!
    - 1 - services-disk16:  `fr360kt0172` - OK!

**Comment by ndushay** [comment]
To conclude: 

- there are 513 complete_moab objects in prescat with "invalid_checksum" 
- the only objects going through preservation-robots that would NOT have been automatically fixed by an M2C run are those with "invalid_checksum" error messages in M2C:  [m2c-invalid-checksum-druids.txt](https://github.com/sul-dlss/preservation_catalog/files/3990365/m2c-invalid-checksum-druids.txt)
- none of the 516 objects (fewer actually - made sure to get some druids before and after the outage)  that ran through preservation-robots during the outage  [prod-druids-alpha.txt](https://github.com/sul-dlss/preservation_catalog/files/3985393/prod-druids-alpha.txt) overlap with the M2C "invalid_checksum" objects

Yes, we still need to address the 513 "invalid_checksum" objects - but that has been a problem, with a stable number, for quite a while now.

tagging @andrewjbtw and @jmartin-sul to let them know;  closing this ticket.
