### ISSUE TITLE
DB Changes for Storage Migration

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1321]
db changes:
- add column for migration timestamp
- add column for old storage root location  <-- can be prepopulated with current storage root

See also #1331 for adding a db column to hold validation error results.

**Comment by jmartin-sul** [comment]
re:
> * add column for old storage root location <-- can be prepopulated with current storage root

this isn't the approach that 1356 took.  i think the suggestion here in this issue to pre-populate is reasonable, but i also think i prefer the approach in the PR, where it starts as `nil`, and remains unset until the actual move.  i think with that approach, it's easier to glean whether the move has actually been attempted/performed.  i am open to arguments in favor of what the ticket describes, though -- maybe i'm missing something and it'd make something else easier if we pre-populated?  but besides the above benefit of signaling whether the move has happened, pre-populating the column would also make the migration a bit more complex to write, and a bit more resource intensive to run.  not super-complex, since it's a pretty simple `update`, but if it's not needed, seems best to omit it.

**Comment by ndushay** [comment]
Aaron explained that pre-populating wasn't a straightforward thing in a migration, and I'm totally ok with dropping that idea.

**Comment by aaron-collier** [comment]
@jmartin-sul yeah, I should have dropped a comment in here. I didn't think pre-populating was appropriate (for the reasons you mention).
