### ISSUE TITLE
(?need for migration MVP?) Way to Run Validation on Moabs on Storage Not Attached to Prescat 

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1323]
Motivation:

When:
- a Moab is migrated to new brick
- passes ops migration md5 comparisons from old location to new brick
- fails a preservation validation check (moab validity, M2C, C2M, CV)

Then:
- we *might* want to run the validation check on the object in the old location

This would imply a way to run validation checks on particular druid on a storage root that is NOT mounted to prescat (either the old root after it is disconnected, or the new brick before it is connected).

NOTE:  this scenario might already be covered by error reports (with complete error messages - from report or from storing all error info in db(not currently done)) and confidence in bitwise copy

-----

commentary:

JLitt says: "Alternatively, Could just compare md5sum outputs from moab on old storage root and new storage root (or similar commandline tool run on the file system). ?"

Naomi says: "not quite - we may need to determine if the moab is valid in addition to checksums (like ... maybe a file didn't copy over, or maybe a file was missing or confused in the old location -- is the copy clean, but the moab was bad originally?)"

**Comment by ndushay** [comment]
I believe running the checks on a root before migration and generating the reports on validation errors before migration may make this moot.  See #1330.

@jmartin-sul @justinlittman do you agree?

**Comment by justinlittman** [comment]
Concur.

**Comment by jmartin-sul** [comment]
also agree.

i think it'd be useful (for the rare moab remediation) to be able to easily run CV on a random moab directory that's not in the catalog.  but i agree that our current migration plan means we don't need that functionality for the storage migration MVP.

i think i'm inclined to close this ticket, since the wording is so specific to the migration.  if we decide we need this functionality afterall, we can either re-ticket or re-open this ticket, as appropriate.

**Comment by jmartin-sul** [comment]
(and of course feel free to reopen if i jumped the gun on closing)
