### ISSUE TITLE
Investigate C2M, M2C, CV Interactions and Audit Result Information

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1330]
- should we do MV and CV on _new brick_ BEFORE we change root w rake task of #1322?
    - on only the druids from the root we are migrating?  (as multiple old storage roots will migrate to a new brick)

- should we do M2C, C2M and CV on _old storage root_ BEFORE we change root with rake task of #1322
    - any objects with validation errors in prescat db will NOT run the validation code - it short-circuits.  See #1324. 

Or is it sufficient to use existing audit info from prescat for old root, and run audits on new root after the migration rake task?

Should we have a new rake task to run C2M for a single storage root?  If yes - spin off a separate issue?

**Comment by justinlittman** [comment]
I'd suggest that we run M2C, C2M and CV on old storage root BEFORE we change root. This will guarantee that PresCat is up to date with the state of the old root.

But not run anything on the new storage root BEFORE we change root. The CV run AFTER the root is changed and comparing the validation errors will be adequate for verifying the move.

Further, running anything BEFORE we change root will muddle the database and create problems for the change root rake task (as there will already be records for the moved moabs).

**Comment by justinlittman** [comment]
To investigate: Interaction between M2C, C2M, and CV including when they are allowed to run and what they put in audit results / record in the DB.

Proposed order to old storage root:
1. M2C
2. C2M
3. CV

**Comment by jmartin-sul** [comment]
here are the answers i've found to the questions in the issue description:

> Q: should we do MV and CV on new brick BEFORE we change root w rake task of #1322?
A: I think I agree with @justinlittman on this:  We should "not run anything on the new storage root BEFORE we change root. The CV run AFTER the root is changed and comparing the validation errors will be adequate for verifying the move."  I also agree that with the present state of things, "running anything BEFORE we change root will muddle the database and create problems for the change root rake task (as there will already be records for the moved moabs)" -- BUT, I have some long ago started (and dropped/still unfinished) work to run checksum validation on random folders on disk, which do not necessarily have to be in the catalog.  The idea is to just subclass the existing CV class to make it usable in that way.  I think this would not be too much work to finish, and could be useful for occasional manual remediation work.  If we _were_ to validate druids on the new storage root before running the rake task to migrate the catalog entries from old root to new, I'd advocate for finishing this work to CV uncataloged moabs, because then we'd avoid the issue jlitt raised here.

More generally, if an object lands with new errors in its new home, it will have to be remediated in its new home no matter what.  Whether that happens before or after the migration of its catalog entry seems like it should be determined based on whatever's convenient to implement -- I don't think it matters much as long as the object gets remediated and the catalog entry ultimately reflects reality.  If we were nuking the copies on old storage immediately after the catalog entry migration, I might feel differently, but I think the plan is to keep the old copies around for a bit, till we're sure the new ones are really ok, and no more remediation is needed?

> Q: [If we run CV on new storage brick before the catalog entry migration, do we run it] on only the druids from the root we are migrating? (as multiple old storage roots will migrate to a new brick)

A: I think this question is _maybe_ moot if we don't run it on the root before the migration, as recommended above.  Or maybe we care about not wasting cycle on unnecessary CV no matter what?  If we did run CV on the new storage root before the catalog entry migration, I would prefer doing it on a predetermined druid list using the as-yet-unwritten uncataloged moab checksum validator.  But I'd also be happy to just see the whole root CVed.

> Q: should we do M2C, C2M and CV on old storage root BEFORE we change root with rake task of #1322

A:  Yes.  I agree w/ @justinlittman that the order should be M2C, C2M, CV (as discussed in a meeting between he and @ndushay and I, iirc).  CV should cover it in terms of fixity checking the moab and confirming that the version in the catalog matches the version seen on disk (if checksum validation is successful, `ChecksumValidator` will then [run the other moab validation stuff](https://github.com/sul-dlss/preservation_catalog/blob/d401ca421bb95717ad3fc15bad8840f7d5ce65d1/app/services/checksum_validator.rb#L32-L39)).  And we should be able to queue CV for all the objects, and it will record errors accordingly for any missing moabs.  So actually, CV probably obviates the need for C2M on this front.

But M2C would be good, to make sure that everything that's on disk is actually noted in the catalog.  As captured in #1318 and #1319, we should dump validation results to e.g. CSV for comparison after the move.  I think we could just use the existing M2C and CV job queuing machinery, since the objects in question will still be in the catalog with an accurate location before the move.

> Q: any objects with validation errors in prescat db will NOT run the validation code - it short-circuits. See #1324.

A:  I don't think this is quite accurate.  `ChecksumValidator` will run checks regardless of the current status, since it runs checksum validation as well as all other checks if checksum validation passes (e.g. does the version disk match the version in the catalog).  `ChecksumValidator` is the audit class that can most authoritatively set status, and it is allowed to run regardless of what the object's current status is.  I actually just saw this happen when pairing on #1303 -- we synchronously ran checksum validation on a couple of the druids with the error described in that issue, and `ChecksumValidator` (via call to `Audit::Checksum.validate_druid(druid)`) was able to correctly update the status from `unexpected_version_on_storage` to `ok`, since the version mismatch error resulted from the robots telling the catalog to update to version 4 of an object after it had already done so.  It is true that validations other than checksum validation will not allow themselves to run on an object that has checksum validation errors.  This was meant to guard against the overwriting of a more concerning status with a less concerning one.  see also #1155, and definitions/invocations of `MoabValidationHandler#can_validate_checksums?`.  There are also some tests that speak to `ChecksumValidator`'s ability to set errors appropriately for non-checksum validation issues, see:  https://github.com/sul-dlss/preservation_catalog/blob/e5c79d10272dd9f418e4a2ab165f3ad661fc6c05/spec/services/checksum_validator_spec.rb#L249-L307

> Q: Or is it sufficient to use existing audit info from prescat for old root, and run audits on new root after the migration rake task?

A: I would prefer to make sure that all the objects being moved had been checksum validated e.g. within the prior week, rather than the usual fixity TTL (currently 90 days).  But this is sorta gut feeling and paranoia on my part, and I think I could be convinced to just go with the status info that's already in the catalog if others believe that's sufficient.  I don't know that we have hard numbers that could guide us either way, unless someone has some relevant hard drive integrity studies handy.

> Q: Should we have a new rake task to run C2M for a single storage root? If yes - spin off a separate issue?

A: My slight inclination is not to add a rake task, and to just cover it in documentation.  We can just queue CV jobs for all druids on the root from rails console.  I believe we'd just do something like:
```ruby
MoabStorageRoot.find_by!(name: 'some_old_storage_root').complete_moabs.find_each(&:validate_checksums!)
```

But i am not strongly opposed to a rake task if others would find that UI much more comfortable than doing the above from rails console.  Either way, it should be done in a screen session!  you'll only be waiting for everything to get queued, not for the checks to finish, but the queuing can still take many minutes (I've done this manually when re-queuing jobs where previous runs had failed due to buggy worker code, and where the failure queue had been cleared).

Note that queuing checksum validation will cause a worker to do validation on the druid.  CVing only objects with expired fixity checks is controlled by only querying for such objects in the cron job definition:  https://github.com/sul-dlss/preservation_catalog/blob/40ca4c3a9279f6cb1961331a2bd03bc28f684cda/config/schedule.rb#L19-L22

**Comment by jmartin-sul** [comment]
would appreciate review of the above for intelligibility (and a quick check for coherence and accuracy based on what you know) from @ndushay and @justinlittman.

**Comment by jmartin-sul** [comment]
i'm going to go ahead and close this, but if there are issues with the write-up, feel free to re-open.

**Comment by justinlittman** [comment]
I've reviewed and agree with the write-up. I'd say I have a slight preference for rake tasks rather than rails console, but it is ever so slight.

**Comment by ndushay** [comment]
i also have a preference for rake task over rails console.  I'm also thinking some of this should go in a wiki - a closed ticket is not where I'd look for this sort of info in the future.

I'll see if I can do that today.

**Comment by ndushay** [comment]
Wiki page created https://github.com/sul-dlss/preservation_catalog/wiki/Validations-for-Moabs.

I DO have concerns about the new storage bricks running validations for ALL their Moabs, as those bricks will have druids from multiple existing storage_roots.  I'm okay tabling the concern for now, but am registering my worry about timely processing (since we only have the weekend)

**Comment by jmartin-sul** [comment]
@ndushay said:
> i also have a preference for rake task over rails console.

sold on the rake task!  fine by me since you and @justinlittman both prefer.  and thinking about it, it does feel more constrained/repeatable, which is probably good here.

>  I'm also thinking some of this should go in a wiki - a closed ticket is not where I'd look for this sort of info in the future. ... Wiki page created

thanks!

> I DO have concerns about the new storage bricks running validations for ALL their Moabs, as those bricks will have druids from multiple existing storage_roots. I'm okay tabling the concern for now, but am registering my worry about timely processing (since we only have one weekend of outage per root migrated)

totally fair.  maybe we can do some benchmarking on stage?  fwiw i don't think it'd be much work to support queueing CV for just the subset of moved druids, since we should have that list handy (it'd be pretty easy to script up on console now, and would be easy to turn into a canned method).

and maybe we could also beef up the prescat worker boxes and increase CV worker count for the migration weekend, if benchmarking or other evidence made us think we'd be unable to audit everything in the window we have given the resources we have allocated now.
