### ISSUE TITLE
preservation catalog controller methods no longer accept prefixed druid, but should

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/preservation_catalog#1421]
**Describe the bug**

When running through the disk migration checklist here: https://github.com/sul-dlss/preservation_catalog/issues/1420 we tried to version an object that was moved to a new disk and got an error at the `preservation-ingest-initiated` step below:

Possibly introduced in #1389 

~~Suspect this may be an instance of passing a druid with a prefix where none is expected.~~ Suspect that preservation catalog is being stricter than it was in the past after the introduction of the openapi spec, and enforcement on requests via committee gem.

```
problem with preservation-ingest-initiated (BackgroundJob: 191190): {:errors=>[{:title=>"Preservation error", :detail=>"Preservation::Client.http_response got 400 from Preservation at v1/objects/druid:gs499vb1742/file: {\"errors\":[{\"status\":\"bad_request\",\"detail\":\"#/paths/~1v1~1objects~1{id}~1file/get/parameters/3/schema does not allow null values\"}]}"}]}
```

**Comment by jmartin-sul** [comment]
arguably this is a regression in pres cat due to #1389, and maybe we should restore its ability to handle both styles of druid in the request (normalized to bare druid for use in the rest of the application), rather than foisting this all of a sudden on the services that call pres cat.

seems like the intent was to be able to handle either and then normalize:
https://github.com/sul-dlss/preservation_catalog/blob/b805d9ff4a4e4adb284791376b59f207232e3c13/app/controllers/application_controller.rb#L50-L52
https://github.com/sul-dlss/preservation_catalog/blob/master/app/controllers/catalog_controller.rb#L50-L52
https://github.com/sul-dlss/preservation_catalog/blob/master/app/controllers/objects_controller.rb#L91-L93

hooray for stage testing, even if inadvertent!

**Comment by jmartin-sul** [comment]
see also https://github.com/sul-dlss/google-books/pull/383 ?

**Comment by mjgiarlo** [comment]
My analysis of this is different from @peetucket's and @jmartin-sul's.

AFAICT, this isn't related to null druids but to the `category` query argument having a null value:

```
# openapi.yml
 272           - name: category
 273             in: query
 274             required: true
 275             example: 'manifest'
 276             schema:
 277               type: string
 278               enum:
 279                 - content
 280                 - manifest
 281                 - metadata
```

Should `category` not be required? Or should the enum change?

FWIW, the druid schema in prescat's openapi spec *should* allow for an optional `druid:` prefix.

**Comment by jmartin-sul** [comment]
thanks for the quick fix, and sorry for the misleading assessment!  i'm an openapi/committee noob.
