### ISSUE TITLE
fix zip temp space cleanup cron job logic, parameterize location it uses

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1576]
pres cat creates archive zip files in the directory specified by `Settings.zip_storage`.  this is `/tmp` by default, but in production it's actually a directory called `/sdr-transfers`.  

currently, it appears that pres cat is only cleaning up md5 files for the zips it generates, and empty directories in the zip temp space:

https://github.com/sul-dlss/preservation_catalog/blob/50bb119490a0a302bae0e8e38900fb2928077c5f/config/schedule.rb#L24-L36

it also appears to be hardcoding the path to the zip temp space.

two tasks to fix the current implementation:
- [ ] fix pres cat's whenever cron definitions to clean up zip files too
- [ ] fix the cleanup command to use `Settings.zip_storage` instead of hard-coding the path

the cleanup `find` command that julian ran yesterday was:  `find /sdr-transfers/ -mindepth 3 -amin +2160 -type f  -delete`

off-hand, i'm not sure if the right thing to do is just to use that to replace the current command (`find /sdr-transfers -mindepth 5 -type f -name "*.md5" -mtime +2 -exec bash -c 'TARGET="{}"; rm -v ${TARGET%md5}*' \;`), or if the right thing to do is to use julian's command as a guide for modifying the current command.

#### alternate approach (maybe not worth the effort at the moment, maybe worth ticketing separately for later)

upon success, `ResultsRecorderJob#perform` does the cleanup of the zip file and the md5 file, after the `publish_result` call.  or, for even more resilience, it could queue a cleanup job (which would require creating a small cleanup job class).

#### more context

the reason that temp space was getting cleaned before was that @julianmorley had his own cleanup script that ran in parallel with the one defined by pres cat's schedule.rb.  this lead to some race conditions and some noisy alerts about trying to delete missing files.  but when that script got turned off for the april preservation storage migration, cleanup of zip files stopped (and we finally ran out of space at the end of last week, triggering us to manually cleanup, and prompting julian to re-add a cron job of his own).

**Comment by jmartin-sul** [comment]
once the fix is merged and deployed, ping @julianmorley so that he can disable his cron job from outside the app, so that we don't get alert noise re: two cleanup crons competing for the same deletions.

**Comment by mjgiarlo** [comment]
@jmartin-sul @julianmorley Now that my first responder shift is over, I've started in earnest on this issue. While this isn't a technically difficult issue, I'm feeling a bit blocked by a question: what are the cleanup **requirements** for the issue? I ask because > 1 implementation options are suggested/mentioned above, those being the different `find` incantations, and I can't really decide between them (or come up with my own) without knowing what the need is here. Marking as blocked until I hear back.

**Comment by mjgiarlo** [comment]
I chatted with @jmartin-sul and below is what we came up with. I believe this issue is now actionable, and I should have it wrapped up soon. Cc: @julianmorley 

# Requirement questions and answers

1. What should be cleaned up?

Empty directories, stale zips (.z????), and stale md5 files.

2. How often should we clean things up?

Every hour, clean up zips and md5s. Every day, clean out empty directories.

3. How to determine what is stale (and, thus, clean-uppable)? 

If any file has not been **accessed** in the past week (`-amin 10080` in `find` syntax), it is stale, so we can safely remove it. This would apply both to zips and md5s.

# Additional requirement

Parameterize the value given to `-amin` above for easier modification over time.

**Comment by jmartin-sul** [comment]
Yup!  Additional background for posterity:  the point of the `TARGET="{}"; rm -v ${TARGET%md5}*` in the current cleanup command was to only delete zip files associated with stale md5 files.  Before creating a zip file, `ZipmakerJob` looks for and touches any associated `md5` file for the zip it would create, and then just delivers that existing zip if it's already present.  This is essentially a circuitous way to get the behavior `-amin` gets us, via the `touch` command and `-mtime`: only clean out things that haven't been _accessed_ in however long (as opposed to cleaning out things that were _created/modified_ however long ago, because by updating mod time upon access, we end up using mod time to represent access time).

Just cleaning out anything that hasn't been accessed in a week feels totally safe.  In practice, I believe all the zips we create should be delivered within a couple days, if not a couple minutes (if the queue has a lot of large objects to zip and deliver, it can take many hours for a zip to be created and delivered).  Additionally, the zip temp space fills relatively slowly, because it's very large:  cleanup was broken from late April (first storage migration) until this issue was filed a couple weeks ago.  So lengthening the cleanup window to a week should be safe in terms of both not deleting too aggressively and in terms of not letting space fill to capacity.

I will say, the string substitution thing _did_ seem to work for me when i tested it just now with a local toy example:
```sh
$ MYCOOLFILENAME='Gemfile.lock' bash -c 'ls ${MYCOOLFILENAME%.lock}*'
Gemfile      Gemfile.lock
```

But since there's a simpler way to get the behavior we want, I still think we should jettison the extra complexity, because just using `-amin` makes things simpler both to read and to maintain.
