### ISSUE TITLE
Make Prescat thread-safe -- class vars

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1881]
from Slack May 11, 2022:

>There’s also one spot in pres cat itself that uses a class variable to memoize info (in druid_version_zip.rb).

![image](https://user-images.githubusercontent.com/96775/170587671-4d85a005-10f6-4ee6-9123-6888ffce775d.png)

This ticket also implies an upgrade to a released moab-versioning gem that includes the fix from https://github.com/sul-dlss/moab-versioning/issues/189

**Comment by ndushay** [comment]
This will also need to upgrade to a released moab-versioning gem that includes the fix from sul-dlssmoab-versioning#189

**Comment by jmartin-sul** [comment]
i'm somewhat inclined to suggest that we just ditch the memoization altogether and call out to `fetch_zip_version` every time (in which case, we should probably just remove the indirection that is the current wrapper method).  all `fetch_zip_version` does is call out to `zip -v` and check/wrangle the output a bit.  the expense of the `zip -v` call seems negligible compared to e.g. actually creating the zip file.

**Comment by ndushay** [comment]
Putting this in ready column, even though PR sul-dlss/moab-versioning/pull/197 for issue sul-dlss/moab-versioning/issues/189 isn't resolved yet.  I think this work can be prepared in any case.

**Comment by justinlittman** [comment]
Blocked by https://github.com/sul-dlss/moab-versioning/issues/189

**Comment by jmartin-sul** [comment]
i think this is actually done: after much discussion, we determined that the moab-versioning gem's one use of a class var is actually thread safe, because of the very particular way in which the variable is initialized (at the time of class loading) and never updated.  see https://github.com/sul-dlss/moab-versioning/pull/197/files

there was a small refactoring around that class var, to make things more readable and more refactorable later.  but the above described behavior should remain completely unchanged, and the rest of that PR's changes were comments about preserving thread safety, and a test attempting to illustrate that current the current implementation is thread safe.

a new version of moab-versioning related to this ticket hasn't yet been released, but considering the above, i don't think any moab-versioning update related to this is actually needed.

closing, feel free to re-open if that seems incorrect.
