### ISSUE TITLE
replace job locking via resque for switch to sidekiq

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1882]
From John in slack on May 11, 2022

>One other thing we'd need to do for sidekiq is port pres cat's job locking, which uses resque's redis methods.  We could either switch to using the redis gem directly (since that's also an indirect dependency of sidekiq anyway).  Or we could try a gem like https://github.com/veeqo/activejob-uniqueness (which at a glance seems maintained, but is just one recommendation from a random blog post found when searching "queue deduplication sidekiq", and the current job locking code has a pretty small footprint anyway).

![image](https://user-images.githubusercontent.com/96775/170587976-ac80e2d7-b57a-4fb8-b4c5-13b4474b4d73.png)

**Comment by justinlittman** [comment]
Can you provide a pointer to where in the codebase the current job locking is implemented?

**Comment by ndushay** [comment]
I believe you will find relevant code in app/jobs/application_job.rb

and also here:

![image](https://user-images.githubusercontent.com/96775/175721750-d2001f79-e5b9-442e-b90d-3c1823d1904e.png)

**Comment by jmartin-sul** [comment]
yup, @ndushay is pointing to the relevant code, i think.

i believe the fix that involves the least change and regression risk might be to just use the `redis` gem directly.  if so, i think the rough outline of the work would be:
- [ ] include the `redis` gem as a direct dependency of pres cat (instead of an implicit dependency via Resque, or Sidekiq if we switch to that)
- [ ] replace the `Resque.redis.*` calls in `application_job.rb` with direct use of the Redis gem.  i've not looked at the redis gem API yet, but i am hoping that the current calls are basically just reaching into the Resque internals, getting its Redis connection, and doing Redis operations with that connection, so i'm hopeful that the change is as simple as something like changing `Resque.redis.*` calls to `get_redis_conn.*` calls, or similar (where `get_redis_conn` might be some simple method we write to get an instance of a Redis connection).
  - [ ] there might also be some configuration to add, as it seems the only place that pays attention right now to the `REDIS_URL` env var is `config/resque.yml`.

thankfully, the job locking has what seems like pretty good test coverage, since we had to port in the functionality of a gem that was no longer fully working for us (resque-lock).  it also seems the tests are pretty agnostic to the locking implementation, so i'm hopeful they won't even need any re-writing.  see [here](https://github.com/sul-dlss/preservation_catalog/blob/0e3e6e4025b8c005ff326e17dad3f6e4e59f3b29/spec/jobs/application_job_spec.rb).

if the above described approach works, i think we should be able to avoid touching the `queue_lock_key` methods in classes outside of `ApplicationJob`.

there's a bit of explanation at the end of `application_job.rb` as to why we ported the locking code in the first place, and a bit of explanation at the top of the file giving a high-level overview of how the locking works, with a pointer to an explanation of this general pattern in Redis as well as a pointer to the original gem code that we used as a starting point.

**Comment by jmartin-sul** [comment]
the PR that implemented this ticket used a slightly different approach to the one described above, but consolidates the use of `Resque.redis` to one helper method, so that it's easier to switch to use of `Sidekiq.redis` when the time comes.
