### ISSUE TITLE
 remove code for multiple moab instances

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1891]
Turns out all this effort was for naught.  Let's simplify this app and remove code that is about supporting multiple moabs.

**Comment by ndushay** [comment]
start with ResultsRecorderJob as we have a ticket to edit that code:  #1860

**Comment by jmartin-sul** [comment]
FWIW, I don't think the multi-moab handling code has any bearing on the ticket about making ResultsRecorderJob's work more resilient.  IIRC, the only part of the replication pipeline that cares about the primary moab is ZipmakerJob (since it needs some moab to work off of).  Either way, I don't see anything about choosing one of multiple CompleteMoab instances when glancing back at ResultsRecorderJob again (e.g. it doesn't query CompleteMoab or worry about the storage root from which replication happened).

I would vote strongly for doing #1860 before digging into reversion of multi-moab at all.  What's there works for our current usage; and I think the short to medium term first-responder pay off of 1860 (fewer dead jobs where a retry is a no-op, less distance from being able to use Sidekiq) is higher and the payoff for this (more intelligibility by everyone and less incomplete cruft).

But I definitely agree that we should do this.  Ceph bought us configurable redundancy of local copies at the file system level, greatly reducing the need for it at the application level.

I also think we should make some effort to map out the work it'd take to remove the multi-moab handling code, as what's there was covered by a number of tickets and PRs, and I don't think we actually want to revert all of them (for instance, regardless of whether we allow multiple moabs, i think it's better to have the archive tables point to the `PreservedObject` instead of the `CompleteMoab`, and that change was part of the multi-moab work; or another, I like the idea of leaving the ability to lock moabs to prevent updates, as that'd make it easier to move moabs between storage roots safely, which is still something that has been occasionally useful for the repository manager, outside any desire for multiple copies of a moab).

Also there's some pres robots code that can be simplified if we do this.

also, yay for end to end integration tests that cover preservation and replication!

**Comment by jmartin-sul** [comment]
Or maybe we don't really have to map it out by digging up old tickets. Another possible approach that might show what changes need to be made:
- add a database constraint limiting us to one CompleteMoab per PreservedObject
- see what tests fail and remove the ones that specifically create multiple moabs
- look for anything that queries CompleteMoab, or reads/sets primary moab, simplify to assume one moab per druid

We could then also consider combining the complete_moabs table into the preserved_objects table, but I'd rather leave that as a separate question and undertaking (and would be slightly against it, at first glance -- it'd simplify queries, but it'd also be a lot of re-writing code, a long database migration, and would then make it much harder to consider multi-moab in the future).

Thinking more about switching to Sidekiq and things that might inform scheduling/priority for this ticket: is multi-moab capability in moab-versioning a significant impediment to making moab-versioning threadsafe?

**Comment by ndushay** [comment]
So the actions to be taken for this from what John said distill down to:

(must be done in order)
- [ ] add a database constraint limiting us to one CompleteMoab per PreservedObject (should probably do that regardless as part of this ticket)
- [ ] see what tests fail and remove the ones that specifically create multiple moabs
- [ ] look for anything that queries CompleteMoab, or reads/sets primary moab, simplify to assume one moab per druid
- [ ] remove the notion of having a primary complete moab (See #1528 for which code to roll back)

separate PRs, or even separate tickets, are welcome.

**Comment by ndushay** [comment]
In qa, for example:

```
3.0.0 :038 > CompleteMoab.count
 => 37557 
3.0.0 :040 > PreservedObject.count
 => 37552 
# difference of 5

 > CompleteMoab.group(:preserved_object_id).having("count(id) > 1").pluck(:preserved_object_id, "count(complete_moabs.id)")
 => [[3941, 2], [527, 2], [1277, 2], [3246, 3]] 

# 2 + 2+ 2 + 3 = 9;  9-4 (4 po ids) = 5, which is the difference in counts - YAY

```

**Comment by ndushay** [comment]
```
> PreservedObject.find(3941).complete_moabs
# shows complete moabs 3942 and 9305

> PreservedObject.find(3941).preserved_objects_primary_moab
 => #<PreservedObjectsPrimaryMoab:0x000055eea3a5f220 id: 3941, preserved_object_id: 3941, complete_moab_id: 3942, created_at: Tue, 11 Jan 2022 08:10:44.911386000 UTC +00:00, updated_at: Tue, 11 Jan 2022 08:10:44.911386000 UTC +00:00> 

# thus
> CompleteMoab.find(9305).destroy

# and then delete from storage:  services-disk-stage2, jm814hj9185
```

**Comment by ndushay** [comment]
### Stage

preserved object ids and counts:

[[9125, 2], 
[28518, 3], 
[28520, 2], 
[23869, 2], 
[32115, 2], 
[9124, 2], 
[9123, 2]]

**Comment by jmartin-sul** [comment]
i think PR #2001 might have finished this issue off?

as such, closing, but feel free to re-open if that seems premature.

**Comment by jmartin-sul** [comment]
ref #1892 (epic ticket)
