### ISSUE TITLE
Document why we need job locking code.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/preservation_catalog#1898]
Currently the documentation explains how the locking works, but it doesn't explain how duplicate jobs would be enqueued or why it's important to prevent two jobs from running at the same time. 

See issue #1882

**Comment by ndushay** [comment]
@jmartin-sul I think this would be for you?  Or maybe @justinlittman at this point?

**Comment by jmartin-sul** [comment]
> I'm not sure our current code does anything to prevent "queue more than one checksum validation job at once". Doesn't it only prevent running more than one at a time?
>
> This seems like a bunch of code that we hope works, but we don't actually have tests that can show that it works and we don't actually know if it's necessary.

The code that checks and sets the lock is in the `before_enqueue` hook, and the code to proactively clear the lock is in the `ensure` block of the `around_perform`.  So the lock should be set when the job is successfully enqueued, checked before the job is enqueued, and it should be proactively cleaned up once the job finishes executing.  It should also expire after the configured amount of time (currently 1 hour).  There are tests that I think/hope illustrate the important behavior on this front, configured for the tests with a lock timeout of 1 second (long enough to actually test expiry in the unit tests, but not so long as to make them take forever relative to the rest of the suite).  The tests use the `:resque` queue adapter, to get them a bit closer to reality.  The tests cover de-duplication on enqueue, successful queuing of non-duplicate messages, proactive cleanup by jobs that finish (whether success or failure), and successful queuing of a job that would've failed had the lock not expired.  See: https://github.com/sul-dlss/preservation_catalog/blob/0e3e6e4025b8c005ff326e17dad3f6e4e59f3b29/spec/jobs/application_job_spec.rb

But perhaps there's some way in which the tests are insufficient that we missed when writing/reviewing.  My recollection is that I got test failures when doing things like taking out the `sleep` on the expiry test, which gave some indication that they were actually exercising the code in a realistic way.

Additionally, since I had to manually queue a bunch of checksum validation jobs today as part of dealing with #1896, I did a bit of manual testing, and confirmed that the job locking still works as expected.  Things I tried:
* attempt to queue a checksum validation job for a druid for which checksum validation had been queued less than an hour ago, and for which the job was currently working: passed, the attempt to queue the job was rejected, with a log message about an unexpired lock.
* re-attempt to queue the same job again after the in progress job finished: passed, the job was queued successfully, with a message about no lock existing (as the original had been cleaned up).
* attempt to queue a job for which an instance had been queued and but not yet performed, but for which the original job was queued over an hour prior: passed, the new job was queued, with a message about acquiring the lock because the existing one had expired.

So, I think we can be reasonably confident that the machinery is working as expected/described.  And it does follow what seems to be an accepted pattern among Redis users for this sort of de-duping?

I agree it's debatable whether this is necessary.  As described above, earlier in development, there was a bit of worry about whether all our job hand-offs worked exactly as expected, and we thought that there might be some situations where e.g. versioning the same druid twice in quick succession might lead to duplicate `ZipmakerJob` queue entries.  If this behavior is hard to port to Sidekiq, I'd be open to dropping it.  But it does seem semantically correct to de-duplicate queue entries as we do, if possible.  I do agree that we are unaware of a specific case where this prevents duplication of jobs by the automated pipeline, but I think the de-duplication gives a bit of extra safeguard if job handoffs/triggers are refactored, and it also safeguards somewhat against accidental re-running of say zipmaker job by a person on the rare occasion when something is being remediated by hand.  So it feels like this has some value, but not so much that I'd want to go to great lengths to save it.

I guess we could search the logs to see how much the de-duplication is actually being exercised, if this turns out to be hard to port, and we're not sure if it's worth the effort?

**Comment by jcoyne** [comment]
Thank you for writing that up @jmartin-sul. That is helpful and if you dropped it into the code I think that would be sufficient.  It seemed to me like a lot of these things are idempotent and wouldn't screw up if more than one ran at once, so it would be good to state "we need an exclusive lock here so that ... or else ...."

**Comment by jmartin-sul** [comment]
np!  can do.  i'd probably leave the exclusive lock note on just `ZipmakerJob` and the delivery jobs, since those are the ones that write to the cloud and to the file system, which seem most prone to non-transactional race conditions.  glad that was a useful explanation 🙂
