### ISSUE TITLE
error ingesting Conrad B.6

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1929]
See:  https://argo.stanford.edu/catalog?f%5Bexploded_tag_ssim%5D%5B%5D=Project+%3A+Conrad+Collection+%3A+Batch+6&f%5Bnonhydrus_apo_title_ssim%5D%5B%5D=Conrad+Collection

it's saying missing stuff for update-catalog step

```
update-catalog : Error completing ingest for druid:bb593yb1501: failed to remove deposit bag (/pres-03/deposit/bb593yb1501): No such file or directory @ apply2files - /pres-03/deposit/bb593yb1501 /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/fileutils.rb:1466:in `unlink'\n/usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/fileutils.rb:1466:in `block in remove_file'\n/usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/fileutils.rb:1471:in `platfo...
```

**Comment by jmartin-sul** [comment]
i think this is an artifact of:
1. pres robots `UpdateCatalog` step cleans up the deposit bag before it tells pres cat that the new version has been added to the moab:  https://github.com/sul-dlss/preservation_robots/blob/53f05d34ac183e9439b605b9b11eb1575a68c8a6/lib/robots/sdr_repo/preservation_ingest/update_catalog.rb#L29-L38
2. due to the re-IP of pres robots' VM on monday (in an attempt to help address ongoing ceph issues), pres robots was for a brief period unable to make network calls to pres cat (firewall config needed updating)
3. so when the `update-catalog` step ran for the items in question, the deposit bags were cleaned up successfully, but the REST calls failed when made to pres cat to let it know the new version had arrived.
4. so the `update-catalog` step failed overall
5. once the firewall config was fixed, i retried this batch of stuff that'd errored on `update-catalog`
6. but then pres robots `update-catalog` failed earlier in the workflow step, because the deposit bag was already gone, so the pres robots `update-catalog` step retries didn't make it to the point of even trying to hit pres cat

attaching a report with the druids that currently have this problem, as well as version number (via the status col): 
[argo_update-catalog_errors_report_2022-08-10.csv](https://github.com/sul-dlss/preservation_catalog/files/9302295/argo_update-catalog_errors_report_2022-08-10.csv)


i think the remediation steps are:
1. run this list through moab-to-catalog using pres cat rails console, so that pres cat picks up the new version: https://github.com/sul-dlss/preservation_catalog#single-druid
2. on workflow service VM CLI, run this list though the rake task for setting a workflow step, and mark `update-catalog` on `preservationIngestWF` `complete` for each of these druid version: `rake workflow:step[druid,workflow,process,version,status]`

in the longer term, we might want to break deposit bag cleanup and making the REST call to pres cat into separate workflow steps.  the current step seems appropriately named fro the hitting pres cat part, so i think we'd be adding a `cleanup-deposit-bag` step before the `update-catalog` step, or something.  these two parts are currently lashed together in the same workflow step, but can each fail independently, and should be retriable independently, i think.

i'll try to deal with these at some point this week.

@andrewjbtw does this assessment sound correct/reasonable?

**Comment by andrewjbtw** [comment]
I think this is correct but it's possible that prescat was already updated with the new version before attempting to remove the deposit bag. I'm not always clear on what order this "step" uses to run its multiple steps. 

I'm assuming m2c would be able to detect whether the new version's bag was actually created, on the off chance that the version numbers don't match what's expected.

**Comment by jmartin-sul** [comment]
> I think this is correct but it's possible that prescat was already updated with the new version before attempting to remove the deposit bag. I'm not always clear on what order this "step" uses to run its multiple steps.
> 
> I'm assuming m2c would be able to detect whether the new version's bag was actually created, on the off chance that the version numbers don't match what's expected.

i think bag cleanup happens first, and moab-to-catalog's automated run is now monthly on the first, so presumably the version change hasn't been caught by the automated M2C yet, and retrying the step fails before getting to pres cat update since bag cleanup fails first.

**Comment by jmartin-sul** [comment]
this morning @andrewjbtw observed that the error about missing moab directory can be sidestepped by creating an empty deposit dir for the druid in question, and retrying the failed workflow step (`update-catalog` will `rmtree` the dummy directory, then attempt the REST call to pres cat to actually signal the version update).  so i went ahead and did that. to fix the `update-catalog` errors.

i got the missing deposit dir paths by using the search results in argo and some javascript (there were 108 errors after andrew and i each tested this process manually on one druid, so i loaded up 100 results per page and did this once for each of 2 pages):
* in firefox, using web developer console, run `errorStrings = []; document.querySelectorAll('dd.blacklight-wf_error_ssim').forEach(function(node) { errorStrings.push(node.textContent) })` on the search results (you can click the `update-catalog` error count from the workflow grid and then do 100 results per page)
* enter`errorStrings` in the web developer console, right click the returned result, select `Copy Object`
* paste the copied JSON in a text editor like sublime that lets you do multiple selection.  highight the first occurrence of `No such file or directory @ apply2files - ` and (e.g. in sublime on mac) `CMD`+`D` till all available entries are selected.  hold shift and move the cursor over till the directories in the error message selections are highlighted too (e.g. `No such file or directory @ apply2files - /pres-03/deposit/bd444bx5955`)
* copy those selections into a new text buffer, then use multiple selection to edit all lines to be like e.g. `mkdir '/pres-03/deposit/bd444bx5955';` and then collapse all those directory creation lines into one line
* run that directory creation command list on pres robots
* go to the next page and do the above steps again for the second page of results
* reset the workflow step from the workflow grid
* watch the errors slowly disappear from the workflow grid after refreshing it

i believe the remaining errors for this facet are due to `validate-moab` failures, and will hopefully be cleaned up this afternoon as andrew and i use some scripts from a similar remediation a couple weeks ago.

**Comment by jmartin-sul** [comment]
for the record, the commands were:

```sh
mkdir '/pres-03/deposit/bd444bx5955'; mkdir '/pres-03/deposit/bf055hg2686'; mkdir '/pres-03/deposit/bt504df0691'; mkdir '/pres-03/deposit/cf392tg6259'; mkdir '/pres-03/deposit/cf779vv0178'; mkdir '/pres-03/deposit/cf901nv0002'; mkdir '/pres-03/deposit/cq000vm6903'; mkdir '/pres-03/deposit/cr040fj2477'; mkdir '/pres-03/deposit/df147nj1754'; mkdir '/pres-03/deposit/df237pz0347'; mkdir '/pres-03/deposit/dg522bq7731'; mkdir '/pres-03/deposit/dn778vf3160'; mkdir '/pres-03/deposit/dn945dv4889'; mkdir '/pres-03/deposit/dq608kr6061'; mkdir '/pres-03/deposit/dz038sn6996'; mkdir '/pres-03/deposit/fb448mg1829'; mkdir '/pres-03/deposit/fc250jv5728'; mkdir '/pres-03/deposit/fd972jg9906'; mkdir '/pres-03/deposit/fg262dn1042'; mkdir '/pres-03/deposit/fn270yd9587'; mkdir '/pres-03/deposit/gb366wf4427'; mkdir '/pres-03/deposit/gb401cd3246'; mkdir '/pres-03/deposit/gd191kq5861'; mkdir '/pres-03/deposit/gk749cc7131'; mkdir '/pres-03/deposit/gp468zb8879'; mkdir '/pres-03/deposit/gr579hx1434'; mkdir '/pres-03/deposit/gt231dk1320'; mkdir '/pres-03/deposit/gv802yd0620'; mkdir '/pres-03/deposit/hg128rk6839'; mkdir '/pres-03/deposit/hg715bz1173'; mkdir '/pres-03/deposit/hj600rx9195'; mkdir '/pres-03/deposit/hk410rn0855'; mkdir '/pres-03/deposit/hx080fc7027'; mkdir '/pres-03/deposit/jt199sv3233'; mkdir '/pres-03/deposit/jz822vn1230'; mkdir '/pres-03/deposit/kb780hz7962'; mkdir '/pres-03/deposit/kg712nk4712'; mkdir '/pres-03/deposit/ks989xr3713'; mkdir '/pres-03/deposit/kt306py6794'; mkdir '/pres-03/deposit/kx489gw0402'; mkdir '/pres-03/deposit/mg776ct6093'; mkdir '/pres-03/deposit/mj005bb5688'; mkdir '/pres-03/deposit/mq025pt1567'; mkdir '/pres-03/deposit/mq731tf7584'; mkdir '/pres-03/deposit/mt202yy3528'; mkdir '/pres-03/deposit/mt399fm1349'; mkdir '/pres-03/deposit/mt983hr0454'; mkdir '/pres-03/deposit/mv358nh7367'; mkdir '/pres-03/deposit/mw082qj7102'; mkdir '/pres-03/deposit/mx914xw6713'; mkdir '/pres-03/deposit/my529gw6660'; mkdir '/pres-03/deposit/nf164qf0453'; mkdir '/pres-03/deposit/ng336jz0115'; mkdir '/pres-03/deposit/nh152tq5032'; mkdir '/pres-03/deposit/ns910nk6328'; mkdir '/pres-03/deposit/pc090ww6948'; mkdir '/pres-03/deposit/pd548ct7388'; mkdir '/pres-03/deposit/ph302yd8187'; mkdir '/pres-03/deposit/ph999pz2444'; mkdir '/pres-03/deposit/pp166cx1672'; mkdir '/pres-03/deposit/pq535hn0742'; mkdir '/pres-03/deposit/pz425tx6952'; mkdir '/pres-03/deposit/pz879jt1267'; mkdir '/pres-03/deposit/qm294kj9845'; mkdir '/pres-03/deposit/qm377hj1415'; mkdir '/pres-03/deposit/qz512gq6840'; mkdir '/pres-03/deposit/rb969cw5285'; mkdir '/pres-03/deposit/rc073qt4668'; mkdir '/pres-03/deposit/rk529wv9130'; mkdir '/pres-03/deposit/rp193xx6845'; mkdir '/pres-03/deposit/rr552ns4243'; mkdir '/pres-03/deposit/sb097hv7762'; mkdir '/pres-03/deposit/sg008kw5329'; mkdir '/pres-03/deposit/sn948qg7021'; mkdir '/pres-03/deposit/ss820rd7680'; mkdir '/pres-03/deposit/sw008dd0105'; mkdir '/pres-03/deposit/sx624xz2066'; mkdir '/pres-03/deposit/tj797xg1803'; mkdir '/pres-03/deposit/tp043hp2764'; mkdir '/pres-03/deposit/tr039yj3052'; mkdir '/pres-03/deposit/vb759hm3265'; mkdir '/pres-03/deposit/vc023yh4865'; mkdir '/pres-03/deposit/vc112qh3477'; mkdir '/pres-03/deposit/vd029fb6904'; mkdir '/pres-03/deposit/vk276zv9273'; mkdir '/pres-03/deposit/vm566mn9094'; mkdir '/pres-03/deposit/vn623js4073'; mkdir '/pres-03/deposit/vn686pv7969'; mkdir '/pres-03/deposit/vp123bg4643'; mkdir '/pres-03/deposit/vq441jz2373'; mkdir '/pres-03/deposit/vq680bt1578'; mkdir '/pres-03/deposit/vr691sf5790'; mkdir '/pres-03/deposit/vs979rn3157'; mkdir '/pres-03/deposit/vy410hb1024'; mkdir '/pres-03/deposit/wd248pz9540'; mkdir '/pres-03/deposit/wf026vp5192'; mkdir '/pres-03/deposit/wf951kp1998'; mkdir '/pres-03/deposit/wg970pf6496'; mkdir '/pres-03/deposit/wh010dx1448'; mkdir '/pres-03/deposit/xn655xx2559'
```

```sh
mkdir '/pres-03/deposit/xp059tj9017'; mkdir '/pres-03/deposit/xq843yn8814'; mkdir '/pres-03/deposit/xv317py0443'; mkdir '/pres-03/deposit/yc927mw3855'; mkdir '/pres-03/deposit/yf596ck9018'; mkdir '/pres-03/deposit/yh479sw9613'; mkdir '/pres-03/deposit/yj997cc6537'; mkdir '/pres-03/deposit/yn259vf0481'
```

**Comment by jmartin-sul** [comment]
@andrewjbtw and i fixed the `validate-moab` errors, and now all of these Conrad maps should be in a good state.  closing, but feel free to re-open if that seems off-base.
