### ISSUE TITLE
(M2C) (SPC) run M2C seeding on prod (blocked by  #273)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#209]
blocked by #68

May need a non-benchmarking (or benchmarking) script in lib/xxx first.  (see #273)

**Comment by jmartin-sul** [comment]
this is in progress.  as of this comment, just over 501119 catalog entries have been processed.  services-disk05 is currently being processed.  the current pace for finishing everything, assuming 1.5 million moabs total, is just over 5 days total.  seeding was started saturday night (just before 10:30 pm), so this puts seeding on track to finish by sometime thursday night.  pace has quickened considerably since the start:  in the first couple hours seeding was running, it was looking more like 10 days total.  hopefully we don't see a slowing before the run finishes.

**Comment by jmartin-sul** [comment]
see https://github.com/sul-dlss/preservation_catalog/wiki/Stats#seeding-the-db
