### ISSUE TITLE
PartReplicationAuditJob: Sum of ZippedMoabVersion child part sizes is less than what is in the Moab

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/preservation_catalog#2277]
Last night, a [Honeybadger exception](https://app.honeybadger.io/projects/54415/faults/101598944) was logged for prescat-prod:

> PartReplicationAuditJob(druid:bd632bd2980, aws_s3_west_2) 3 on aws_s3_west_2: Sum of ZippedMoabVersion child part sizes (37114) is less than what is in the Moab: 40216

@jmartin-sul 💬 (cc: @andrewjbtw)
> well, unsurprised, if disappointed, to learn that this problem was detected on the audit's first run.
> 
>i'm hoping the error is confined to before we added the non-audit version of this check (ZipmakerJob throwing an error if it generates too small a zip).  vague worries that won't be the case. this definitely warrants some investigation/remediation. i think the thing to do when errors are detected is:
> 
> * delete the incomplete zip moab versions that were detected
> * clear up the related database rows using Replication::FailureRemediator.prune_replication_failures on the affected druid versions (it'll check the cloud and refrain from deleting DB records that have cloud copies, as a safeguard)
> * trigger replication (PreservedObject#create_zipped_moab_versions!) on the druids that got cleaned up (it'll just fill in the missing versions on the endpoints that need them).
> 
> fixing this all at once is probably bigger than an FR task, but capturing the issue could be an FR task, as could chipping away at it incrementally once we have an issue to track progress.

If helpful to test this in stage, we saw this on stage around the same time: https://app.honeybadger.io/projects/54415/faults/101598898 _**note 2023-11-06**_: @jmartin-sul just noticed that the linked HB alert also captures things like `PartReplicationAuditJob(druid:xt299pt7593, ibm_us_south) replicated md5 mismatch` -- but this ticket is specifically just about the detection of what appear to be _incomplete_ (because they're smaller than expected) zips in the cloud.  HB must be collating multiple types of error detected by `PartReplicationAuditJob` as part of one alert bucket.  [here's a link to one specific prod alert from 2023-11-06](https://app.honeybadger.io/projects/54415/faults/101598944/01HEHPF08MQ5VJ7MSFG7GT1HFF#notice-summary) for this ticket's problem, instead of the overall HB alert.

**Comment by mjgiarlo** [comment]
Consider too surfacing errors of this type in the preservation dashboard so they're more visible.

**Comment by justinlittman** [comment]
Ops task: https://github.com/sul-dlss/operations-tasks/issues/3517

**Comment by jmartin-sul** [comment]
> Consider too surfacing errors of this type in the preservation dashboard so they're more visible.

notes from a bit of [slack discussion](https://stanfordlib.slack.com/archives/C04D8DJDRJ9/p1699303517568949) yesterday:
1. surfacing this in the dashboard probably implies tracking this error status in the DB so that it's easily queryable?
2. my initial gut feeling is something like: this is probably a new status field on the `ZippedMoabVersion`.  `ZipPart` feels like the wrong place to add a status code because this situation can be about the sum of many zip parts.  and iirc, the only other status field is on `MoabRecord`, which also feels like the wrong home, especially after [the data model change](https://github.com/sul-dlss/preservation_catalog/pull/1589) that made `PreservedObject` the parent of `ZippedMoabVersion` (a reasonable change even if the motivating feature didn't come to fruition).
3. if one really wanted to, this could be queried for now, though it'd be a bit knotty and i'm not sure how performant it'd be.  but you could query for this by seeing which zipped moab versions total up to less than their associated `MoabRecord`'s `size` (sum `zip_parts.size`, grouped by druid/version/endpoint, join back to `moab_records` via `preserved_objects`, see which `zip_parts.size` totals are less than the associated `moab_records.size` field, i think using a `having` clause for that comparison).

one last thought: we're hopeful that we're no longer able to create new instances of this error since the audit size check that's alerting here was preceded by a similar size check that should prevent us from even uploading incomplete archive zips.  so that may mean it's not worth the effort to write a query for this situation since there's an audit, and it may also mean it's not worth altering the data model to make this more easily queryable.  exporting the honeybadger error list and getting the druids that way, as justin did above, is likely the way to go if we're just fixing old errors and not creating new ones.

will query to see whether any druids with this issue are younger than the size check that should prevent upload of incomplete archive zips...

**Comment by justinlittman** [comment]
This is done. Replication audits pass.
