### ISSUE TITLE
(SPC) feature flag for perf data of seeding

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#273]
For the code that seeds the catalog (called from rake task?) have a feature flag that can turn on

- newrelic performance tracking?  OR
- ruby's benchmark code used for performance tracking OR
- ???

**Comment by tallenaz** [comment]
for how to set up newrelic, see, for example, https://github.com/sul-dlss/exhibits/search?q=newrelic

**Comment by jmartin-sul** [comment]
if we use newrelic, i'd vote for doing this via the settings available in newrelic.yml.  IIRC, there is a flag for whether perf data is sent to newrelic, and a flag for whether profiling is even run.  the latter seems like the more useful one, if we're concerned about profiling overhead (but also, the more obvious one to toggle is the one for sending the data to newrelic, based on what i remember from last time i looked at newrelic's documentation).

**Comment by tallenaz** [comment]
The `monitor_mode`flag lets the agent collects performance data, and reports it to the New Relic service. It looks like that defaults to `true` (for example, the exhibits test environment sets it to false, while prod and stage don't set it at all).  As far as I can tell, we can't access profiling, because that requires a paid account, which ours is not. I tried to verify this by attempting to look at the "Thread Profiler" in one of our apps, and was greeted by an option to upgrade. If there are other profiling tools available via newrelic, I haven't found them yet.

I'd say that because it is simple enough to set up, we should set up basic monitoring, and talk about another way to track profiling overhead.

**Comment by tallenaz** [comment]
newrelic is installed on stage, but off for the moment. looking into porting argo's profiler into PC.

**Comment by ndushay** [comment]
Is this covered by the two flavors of seeding rake task?

**Comment by jmartin-sul** [comment]
yup, i think this is covered by the two flavors of rake task and by `newrelic.yml`.  closing with the same rationale as #274.
