### ISSUE TITLE
(M2C) feature flag / separate rake task for profiling data of M2C existence check (blocked by #268?)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#274]
For the M2C existence check code (called from rake task?) have a feature flag that can turn on

- newrelic performance tracking?  OR
- ruby's benchmark code used for performance tracking OR
- ???

See also #273

**Comment by jmartin-sul** [comment]
if we use newrelic, i'd vote for doing this via the settings available in newrelic.yml.  IIRC, there is a flag for whether perf data is sent to newrelic, and a flag for whether profiling is even run.  the latter seems like the more useful one, if we're concerned about profiling overhead (but also, the more obvious one to toggle is the one for sending the data to newrelic, based on what i remember from last time i looked at newrelic's documentation).

**Comment by jmartin-sul** [comment]
since we can enable/disable new relic via its `newrelic.yml` settings file, and since profiling for seeding has to explicitly be chosen by calling the rake task with the right param, i think we can close this.

if we add more profiling, we can keep in mind that we should make it easy to disable or enable via settings.

**Comment by ndushay** [comment]
this one is for M2C existing check, not seeding.  So I think this one should still be open.

**Comment by jmartin-sul** [comment]
ah yeah, whoops, sorry

**Comment by ndushay** [comment]
this is now duplicated by #395. closing.
