### ISSUE TITLE
consistently use UTC timestamps

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#320]
-  UTC vs local time for logging timestamps; Agree on datetime fields 
- timestamp fields are written consistently

**Comment by ndushay** [comment]
for example, PC.last_checked_on_storage  and PC.created_at , etc.   Also, bigint timestamp fields (for sorting??)

**Comment by tingulfsen** [comment]
I'd like to suggest that we use the ISO 8601 format for logging, using the current local timezone. For example:

```
Time.current.getlocal.iso8601(3)
=> "2017-12-22T12:53:06.198-08:00"
```

**Comment by ndushay** [comment]
? should rake task runners use UTC?  Not hard if a program; harder if a person.

John votes for UTC always
Naomi votes for Pacific always (until replication to other time zones makes that a mess, so she changes her vote)

**Comment by atz** [comment]
I agree w/ @tingulfsen: ISO8601 is the standard.  Based on my experience with mutli-node systems though, in my opinion, UTC is preferable to local.  There is only one UTC.  There are many locals.  If you ever have to do analysis that includes logs from switches, VPN, AWS, i.e. any other part of the network, UTC is the only thing that is reliably common ground.  

A few points here:
- Most important, USE A TIMEZONE.  Otherwise the value is uncertain.
- Second, use that TZ consistently.
- Third, which TZ is best?

Outputting to humans in whatever timezone is most accommodating to them is 100% fine, but that should be a separate concern from internal stuff (persistence, logging).

**Comment by atz** [comment]
The environment for these executions has changed since this was ticketed, since we don't have long running individual processes anymore, preferring atomic asynchronous jobs.  Similarly, the profiling code is mostly gone (since the real work is happening on different processes and different machines).
