### ISSUE TITLE
ReST(?) call for MV (with D2D) (possibly blocked by MV #91)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#339]
When humans are trying to fix moabs, they will want:
- way to get ALL known errors for a Moab (sul-dlss/moab-versioning#91)
- way to do ReST call manually to recheck until moab is valid (this ticket)

**Comment by jmartin-sul** [comment]
possibly/tangentially related to #443?

**Comment by jmartin-sul** [comment]
humans who are fixing moabs are likely already on the command line, since remediation seems like it'd require wrangling files.  if they're comfortable doing that, they're likely also comfortable running validation manually from the rails console.

closing, but of course feel free to reopen if it seems like i'm off-base.
