### ISSUE TITLE
(M2C) workflow error messages update dor solr index for argo

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#421]
It *may* require switching to using dor-services.  Note the Dor::Config object with a solr_url ...  see https://github.com/sul-dlss/dor-services  (readme).

Or perhaps dor-workflow-services gem could get a PR that will allow explicit calls to update solr ...

I note particularly the `to_solr` method https://github.com/sul-dlss/dor-services/blob/master/lib/dor/workflow/document.rb#L90-L131

in individual item objects, perhaps we need this????   https://github.com/sul-dlss/dor-services/blob/master/lib/dor/datastreams/workflow_ds.rb

**Comment by jmartin-sul** [comment]
here is my understanding of the indexing process, from looking at the code, talking w/ @ndushay, and getting some second hand info from @LynnMcRae via @ndushay:
* we update the workflow service, as in PR #426
* this should update the workflow service db, which should trigger an update to the workflow data stream on the fedora object.  the update to the fedora object should trigger an asynchronous reindexing call to refresh argo's solr document for the fedora object (from slack chag w/ @ndushay:  "Lynn thinks that calling dor workflow rest endpoint should update fedora and trigger indexing")
* this could be laggy, since fedora will trigger an update by queuing a reindex request, which will not be fulfilled synchronously (it'll sit in argo's activemq queue till it gets picked up by dor_indexing_app).
* @ndushay indicated that in testing, @SaravShah and @tingulfsen found that hitting the reindex button manually updated the solr document properly.
  * that indicates to me that we could continue with the bad habit of forcing a synchronous-ish reindex by calling dor-indexing-app directly, and forcing a reindex immediately.  the rest request blocks, so the result of the call to dor-indexing-app should indicate whether the indexing attempt was a success.
  * if we have a tolerance for lag, i'd suggest that we test seeing whether the indexing request eventually comes through, since this pattern of expecting synchronous indexing is rather frowned upon generally, and is out of line with our desire to embrace a more pipeline system.  [citation - who?]
    * @ndushay worries that stage might not be hooked up properly for dealing with the indexing queue.  in my recollection, it was, since that's where the dor-indexing-app work has been tested first, but @cbeer or @drh-stanford would know better than i, as they've dealt with that part of our infrastructure more recently.

**Comment by ndushay** [comment]
We are now using the workflow ReST api to send the errors and that will automagically update the DOR index.

Our previous approach, which was to use dor-workflow-service gem, also automagically updated the DOR index.

Therefore i am closing this ticket.
