### ISSUE TITLE
update_version:  if skipping versions, report as its own  error (still update catalog)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#451]
@blalbrit says that he would like an error reported to dor-workflows when **update_version** (as called by **ingest robot**):
- skips a version (e.g.  incoming version is 4, but PC  version is 2).   We should go ahead and update the preserved copy object, but we should also report the skip to dor workflows and log it.
- incoming <= version in the catalog (this is an ERROR for an update_version call).  We should *not* change the version in the catalog, we should set an error status (I think) and we should report the error to dor workflows and log it.

The above behavior also applies to what we want when M2C existence check finds incoming version > catalog version:
- if incoming version <= version in catalog:  error condition;  status becomes error, error reported in dor workflows, logs, etc.
- incoming version skips version in catalog (online moab is version 4, but catalog is version 2):  update PC object, report skip to dor workflows and log it.

**Comment by jmartin-sul** [comment]
we'd want confirmation from @andrewjbtw if we make changes on this front, but revisiting this ticket while doing some backlog grooming w/ @edsu, i think:
* "skips a version (e.g. incoming version is 4, but PC version is 2). We should go ahead and update the preserved copy object, but we should also report the skip to dor workflows and log it."  -- i'd think we probably want to e.g. log and honeybadger alert, but if this is a somewhat expected (and not very worrisome) situation, i'd say we probably don't want to report an error to workflow service, because we don't want to gate accessioning based on clearing this (non?) error?  we also have added the dor-services-app event service since this ticket was filed -- perhaps that'd be a more appropriate reporting destination?
* warrants looking for confirmation, but i think this is already the case?  "incoming <= version in the catalog (this is an ERROR for an update_version call). We should not change the version in the catalog, we should set an error status (I think) and we should report the error to dor workflows and log it."
  * if we do have to make a change on this front, might be better as a separate ticket?

**Comment by ndushay** [comment]
@jmartin-sul this seems worth a discussion with @andrewjbtw.  Maybe this no longer happens.  Maybe it does happen, silently.  What does Andrew know?  What does he wish to happen?

Maybe the answers will allow us to just close the ticket.

**Comment by andrewjbtw** [comment]
I've never seen this and must have missed the earlier mention of me while on vacation. I now wonder if there are moabs where this happened and what we should do about them. I don't think it's possible to get into this situation now.

**Comment by andrewjbtw** [comment]
I'm fairly certain this would result in an error in accessionWF, probably at sdr-ingest-transfer. There used to be a lot of version mismatch errors but I don't remember seeing a version skip on the Moab side, just on the SDR/Fedora side. We have literally thousands of druids where there's a version with the name "fix version mismatch" where the numbers were put back into sync.

**Comment by ndushay** [comment]
So I think the questions for @andrewjbtw are:

For (incoming version is 4, but prescat version is 2) - do you want us to add a check to see if we are skipping versions, and if so, to ... do what?  notify HB?  report to workflows?

For (incoming version is 2 but prescat version is 3) - we think what we are doing now is fine.  Do you disagree?

**Comment by andrewjbtw** [comment]
I think we should probably close this rather than try to figure out if a situation that applied in 2018 and has not happened in the past two years still applies. There should already be notifications set up in both accessionWF and preservationIngestWF if versions don't match the expected value, though it would be good to verify. I definitely saw version match errors (off by 1) in HB and the workflow grid while doing preservation remediation this year.

My only question is if a moab already in preservation has a version skip. If so, some remediation might be in order. I think (hope) that a skipped version would result in an audit failure. There was a lot of manual versionMetadata editing in the Fedora era that could give the impression that a version skip was possible, but I'm 95% certain that even when the Argo interface showed a jump from version 1 to version 3, the Moab incremented sequentially, with versionMetadata editing being the path to bringing things back in sync for subsequent versions.

**Comment by ndushay** [comment]
I'm going to close this.  I remember talking to Ben about version skips, but it may have been theoretical, rather than actual.  I'm going to close this ticket.
