### ISSUE TITLE
Turn Rails.logger.warn to Rails.logger.error in workflow_errors_reporter.rb

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#502]
in `workflow_errors_reporter.rb:6` if the `response.status` is not 204 then we should get a message in the logs that the request didn't go through. We expect that there shouldn't be many of these...

(when figuring out why the wf put request was not being sent in prod, this would have helped)

**Comment by jmartin-sul** [comment]
the `update_workflow` method:
https://github.com/sul-dlss/preservation_catalog/blob/80d620af7a332e76cd0749d966ecc0532f23eb57/app/services/workflow_errors_reporter.rb#L6-L18

i think we want this part to log an `error`:
https://github.com/sul-dlss/preservation_catalog/blob/80d620af7a332e76cd0749d966ecc0532f23eb57/app/services/workflow_errors_reporter.rb#L12-L13

since we don't expect that to happen often.

alternatively, we could set the prod log level to `warn`.  but either way, this seems like an event that should show up in the prod logs.
