### ISSUE TITLE
(Replication) which message queuing software should we use?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#607]
Redis?
ActiveMQ?
PC database tables?
other?

~~The same Redis instance we use for robots?~~

Would like clarity on requirements of messaging system (see R3 google doc https://docs.google.com/document/d/1ofCfmeZ_lx8cpMUFbCb1Bt2R3TSna48oPuQT8YphSvg ), and pros / cons of contenders

**Comment by ndushay** [comment]
Cannot use same instance of message queue as another application;  must be ONLY for preservation catalog functionality.

**Comment by ndushay** [comment]
IFF we use Redis, we could use Redis as the temporary TCR for zip file checksums

**Comment by jmartin-sul** [comment]
Discussed with @atz:  we both agree that Resque/Redis seems like the way to go, for the following reasons:
* it's robust, and a messaging queue that we have experience with in production on the infrastructure team.
* per @ndushay's observation last week, it has a nice built in dashboard that gives visibility into queue state (and potential viewers of this queue use Resque to watch robots, and so our target audience has experience with it).
* we couldn't identify any shortcomings that'd make it inappropriate for this work.

We also discussed Sidekiq, but we knew of no advantages it has over Resque, and we suspect that the infrastructure team has less experience with it than with Resque.

We're putting this in the "needs review" column so other people can vet our logic.  If others agree with our conslusion, I think we can start ticketing what we need to ticket to get ourselves setup with Resque for Pres Cat work (@julianmorley mentioned a mandate to not use the existing Redis/Resque instances, IIRC, but I can't remember the rationale).

**Comment by ndushay** [comment]
@tallenaz this possible Resque thing is for replication, not robots.  But since that is currently envisioned as part of PreservationCatalog, your concern remains valid.

**Comment by ndushay** [comment]
I find it hard to believe I would find anything useful that you haven't already seen, but just in case:
- puppet-redis ?

**Comment by jmartin-sul** [comment]
_

it appears that sidekiq requires that all the code it runs be threadsafe, which our code very likely isn't (since it uses memoization, which is not threadsafe without the explicit use of a `Mutex`).

also, it appears that resque is more resilient in terms of preventing memory leaks and gracefully handling crashed or hung workers.

https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#threading
https://bearmetal.eu/theden/how-do-i-know-whether-my-rails-app-is-thread-safe-or-not/
https://github.com/resque/resque/blob/master/README.markdown
https://stackoverflow.com/questions/11580954/resque-vs-sidekiq _note: kinda old_

@atz @tallenaz @ndushay @SaravShah @julianmorley:  any objection to settling on resque and closing this issue?

**Comment by tallenaz** [comment]
No objections here.

**Comment by atz** [comment]
Settled

**Comment by jmartin-sul** [comment]
resque it is.
