### ISSUE TITLE
(CV) create second prod VM for PC on new VM farm

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#616]
to facilitate running CV in parallel

Note:  In NDCCH, no two VMs should be on the same physical host

**Comment by tallenaz** [comment]
Kam and I think there's a way to set a rule in VMWare to restrict vms to physical hosts, but aren't sure about how. I'll bring this up in the next systeam meeting. In the meantime, we do know of a kludge which is to just move them to different hosts after they're spun up and trust that nothing short of a hardware crash will move them elsewhere.

**Comment by tallenaz** [comment]
Connects to #173

**Comment by julianmorley** [comment]
It's an affinity rule. Or an anti-affinity rule.
https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.resmgmt.doc/GUID-FF28F29C-8B67-4EFF-A2EF-63B3537E6934.html

**Comment by julianmorley** [comment]
One idea; create a host group for all the ESXi hosts.
Create two VM groups; one for even-numbered VMs, one for odd-numbered VMs.
Create an affinity rule(s) that keep all the odd-numbered VMs on different members of the host group, and that keep all the even-numbered VMs on different hosts in the host group. So at most we'd have 2 VMs on any 1 host, and it gives us some wiggle room for when the number of total checking VMs are > that the number of physical hosts available.

**Comment by tallenaz** [comment]
I think we can follow @julianmorley's suggestion by creating 2 vm-vm affinity rules. Each rule will include half of the preservation vms and will specify that those vms must run on different hosts. This way, we won't have to create a dedicated host group for all ESXi hosts.

The other thought I have here is that we have terraform set up to create a pool alphabetically, instead of numerically, so that if we want to create even and odd numbered vms, we'll have to forego the "pool" setup, and create each one as a separate terraform resource. We might want to create them numerically since if we point one vm at one storage root, things will get awkward after we get 27 storage roots (we're already more than halfway there) and the last machine we spun up was `preservation-catalog-prod-z`.
