### ISSUE TITLE
CV ReST(?) call for single druid

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#631]
https://github.com/sul-dlss/preservation_catalog/issues/612

We certainly don't want to make a blocking ReST call for CV, but might we want to trigger it for ReST service?

**Comment by atz** [comment]
We don't have an actual user for this REST feature, afaict.  CV is generally performed via async job, so that makes it inherently unblocking.  

Everything gets CV'd w/in its TTL, so I'm closing this as no longer projected as a requirement.  The first step, if reopening or reticketing, should be to determine what system might actually be calling here and make sure that the integration actually makes sense.  Outside of PresCat, people caring about triggering one-off CV seems far less useful than 100 other possible features, since everything gets CV'd automatically eventually anyway.
