### ISSUE TITLE
(R) Implement Plexer Worker (blocked by #713)

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#709]
- given a druid what endpoints should i live on?

- will need a scope and or a helper method on models? which we will use that query to help determine where the zip file should live (endpoints)

- also use that query to create the initial pres_copy before queueing to the zipmaker worker and at the end to see what we should have vs what we actually have (Not related to the implementation for the plexer worker, but we will be using this elsewhere.)

**Comment by atz** [comment]
@jmartin-sul LMK when you have a suitable branch point with the policy logic

**Comment by jmartin-sul** [comment]
@atz here's a branch with the "what endpoints need a pres copy for this druid?" query:
https://github.com/sul-dlss/preservation_catalog/tree/target-archive-endpoints

haven't written any tests yet, but did some manual testing in rails console, and it appears to be working.

on that branch, you'll also see the beginnings of the logic to create as-yet unreplicated pres copies.

to get what you're looking for in your work, i think you'd just invoke `Endpoint.target_endpoints(druid).archive` to get the list of endpoints you care about.  that's all in the first commit.  though i pushed up the whole branch, because i also started in on seeding archive endpoints, which is still very much WIP, but figured you might want to glance at that if you had a moment, since it's building off the `HostSettings` work you and @tallenaz did.
