### ISSUE TITLE
(C2M) rake task to run pohandler.update_version_after_validation on those objects with status "unexpected version"

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#766]
We have already encountered a case where we want to run M2C on objects identified as "unexpected version" by CV ...

This is scope creep, so if it is taking more than a couple hours ... STOP.

**Comment by ndushay** [comment]
created branch 766-c2m-bad-status-only.   It has:

- `PreservedCopy`: scope `status_version_audit` that retrieves records with unexpected_version or unknown_status
-  `catalog_to_moab`: add `update_version_per_status` methods for single dir and all dirs -- but they incorrectly call c2m.check_catalog_version, when we'd really like for it to call pohandler.update_version_after_validation
- `Rakefile`: add `c2m_update_version_per_status` tasks

**Comment by ndushay** [comment]
Decision was made to see where we are after running M2C and C2M as crons in prod for a bit.

**Comment by jmartin-sul** [comment]
if we need to do this as more than a one-off again, we can formalize this into a canned method in the codebase.  for now, seems easy enough to do this in console as needed, e.g.:
```ruby
druid_list = CompleteMoab.find_by(status: 'unexpected_version').pluck(:druid)
druid_list.each |druid| do
  MoabToCatalog.check_existence_for_druid(druid)
end
```

while looking at `MoabToCatalog`, i also noticed there's a method in there that will check a druid list from a CSV file (`.check_existence_for_druid_list`).

so i think we can consider this closed, since it seems like demand for this functionality is low, and little assembly is required to get it anyway.
