### ISSUE TITLE
(R) select how to kick off replication from create/update catalog

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#812]
creating a new complete_moab or updating an online complete_moab with a new version should trigger replication ... via zipmaker.perform_later(xxx)

Options:
- do this in pohandler? - create, create_after_validation, update_version, update_version_after_validation
- Do this as hook in `CompleteMoab` model for `after_create`, `after_update`?  (note something about not causing extra rows Endpoints)
- Do this in `PreservedObject.create_copies`?
- ~~Do this as an after hook in controller?~~ b/c don't only want via controller.

This ticket is about deciding what approach to take.   That discussion should spawn the tickets to do the work.

See #913

**Comment by atz** [comment]
Putting hooks on `PreservationCopy` seems most conventional, with the unfortunate complexity of our model doing double-duty for both `online` and `archive` objects.  To replication it 100% doesn't matter though, since `ZipmakerJob.perform_later` only gets a druid and version anyway, but for overall logic, we may want to only enqueue for archive PCs, for example.

**Comment by atz** [comment]
It is now easier to imagine an `after_create` hook, since the PC/APC models have been fully separated.

**Comment by jmartin-sul** [comment]
i believe this is code complete with the merge of #1018 to master.  needs to be deployed to stage and prod and allowed to run for real, but i'm going to close this, and we can open bugs if we find problems.  i'll also open a small issue for tagging, deploying, and confirming that things are working.
