### ISSUE TITLE
>10GB Moab replication

### ISSUE THREAD

**Issue by atz** [sul-dlss/preservation_catalog#850]
We designed under the constraint that only objects smaller than 10GB will enter the replication pipeline, but we did not put in any protection to guarantee that.

Currently the zip command will produce “split” zips at 10GB, but since we have the assumption everything fits inside that, we never replicate beyond one zip.

**Comment by julianmorley** [comment]
This constraint should apply on a per-worker basis; we will (for now, during initial seeding) want workers to not process > 10GB moabs. But we will want to be able to create a worker that will work on those big objects - we're just treating them as a special case, likely to be on a dedicated transfer box or talking to a Snowball instead of S3.

**Comment by julianmorley** [comment]
Or to put it another way - whilst we're seeding the cloud buckets, we want to constrain our general workers to not process moabs > 10GB. We do, however, want to be able to create a worker that 
a) does not have this limit and 
b) only processes Druids that we give it (rather than looking for work on the general queue).

The limit also applies to the size of the *version* directory, not the size of the entire Moab object - if we have an existing Moab > 10GB that receives a new version with 25KB of changes in it, we want that to be processed by the general worker population.

**Comment by ndushay** [comment]
Depends on how we set up triggers -- as an after_create hook???  or does it need to be in the worker before_enqueue or ....

**Comment by atz** [comment]
This protection can exist at in different forms at different places (or nowhere if the fix is to make the existing workers and DB handle many zip parts).  Since we currently have nothing, the implementor has a lot of freedom what they want to pursue first.

**Comment by atz** [comment]
Right, we're talking about Moab *version* directory size, which is what should correspond with a `PreservedCopy` row.  

@julianmorley Is zipping to 10GB chunks an explicit preference or was that just a technically pragmatic move?  Would we be OK w/ the second worker (or wherever) producing a single 100GB zip, for example? 

Given that our S3 client libraries already can do multi-threaded multi-part upload (and download), it seems like we could easily throw anything that we already have mounted on disk, as long as we can fit it in zip transfer storage.

**Comment by atz** [comment]
**Some** chunking is going to be required (we have multi-TB objects).  `10GB` is the threshold we picked.  

Additional data modeling for zip parts is required.  It is blocked by #927 (splitting PC models).  

ALL preservation workers will have to change, since they will need to know about zip parts:
- Zipmaker will have to pass **at least** the number of parts created, or more concretely, the part filenames, either of which will have to come from a glob of the expected output of `zip`, since we don't receive return data about segmentation
- Plexer will make different rows, and plex **per part**, not per druid/version
- Delivery workers no longer deliver a druid/version, only a druid/version/part
- `ResultsRecorder` has to update parts rows, and map parts back together to update APC

The good news is, if we do that, we won't need separate queues for anything.

**Comment by atz** [comment]
Documenting here that when size dictates, `zip` will produce "split" files named like:
```
filename.z01
filename.z02
filename.z03
...
filename.z101
filename.z102
filename.z103
...
filename.zip
```
