### ISSUE TITLE
log rotate for C2M and M2C batch logs uses xxx.log.1 xxx.log.2 but long term backup ignores those

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#857]
Unlike the Rails production log, the logs for c2m and m2c seem to automagically be rotating to:

```
-rw-rw-r-- 1 pres pres        0 May 26 05:00 c2m-err.log
-rw-rw-r-- 1 pres pres        0 Jun 10 03:46 c2m.log
-rw-rw-r-- 1 pres pres     3910 Jun 10 03:46 c2m.log.1
-rw-rw-r-- 1 pres pres     7820 Jun  3 03:06 c2m.log.2
-rw-rw-r-- 1 pres pres      498 May 28 03:17 c2m.log-20180528.gz
-rw-rw-r-- 1 pres pres      512 May 29 03:36 c2m.log-20180529.gz
-rw-rw-r-- 1 pres pres     3910 May 27 03:44 c2m.log.3
```

But our puppet setup to write out old logs (and probably to clean old stuff out of log directory?) only goes for xxx.log

https://github.com/sul-dlss/puppet/blob/production/hieradata/node/preservation-catalog-prod-01.stanford.edu.eyaml#L121-L161

So two related tasks:

- I think we want the C2M and M2C logs to rotate like Rails production.log rotates
- We need to ensure we are backing up all those logs

And a third task in #858 -- do we want the output currently going to Rails production.log  from these tasks to be in the task specific log, or do we want to leave it in production.log?    If the latter, we might consider at least renaming the logs as they are now to indicate it is only the output from the rake task itself, not from the checks.

**Comment by tallenaz** [comment]
First, a simple point: the logrotate rules for the c2m and m2c logs were set up with `nodateext` instead of `dateext`, which explains the decimal suffixes, as opposed to datestamps. 

Second, a more complicated point:  I think the idea was to ship those logs off less frequently than the rails prod log, because they're also set to rotate every week. However, because of they way logrotate is set up on rails production machines, *every* log in the standard log directory (including c2m and m2c logs) will get rotated and shipped off to afs daily. We could set them up to rotate and ship less frequently, but then we'd have to relocate them.

About the two related tasks, then: if all we want if for the c2m and m2c logs to rotate and ship like the rails production log, then all we need to do is remove the additional logrotate rules for those particular logs. But if we want them to rotate less frequently, we'll have to relocate them and amend the rules to use `dateext`and point to their new locations.

I don't have a strong opinion about the third task.
