### ISSUE TITLE
Backlog of Replication

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#866]
from storytime 2018-06-11: Joe and Julian will discuss:

"We have significant “catchup” to do - we need to archive all existing versions of all of our Moabs.  This is a separate problem from  “replicate the latest version as it is added to prescat”.

When we have the ability to send druid/versions to endpoints, then we will need to be sure we can create a temporary endpoint for a snowball (e.g. for all druid/versions on root 2);  then we run a replication job to that endpoint."

This will determine what is in scope for team for work cycle.

**Comment by julianmorley** [comment]
Issues:
* get a Snowball
* get a Snowball onto the appropriate network segment in Forsythe or NDCCH in an expeditious manner (time-based billing for Snowball ... the clock starts ticking as soon as it's delivered)
* configure a worker node to process an arbitrary set of druids from NFS to the Snowball
* Send the Snowball back when full
* Ingest Snowball content to correct bucket in AWS, run C2A to verify.

**Comment by julianmorley** [comment]
Talked to Ryan@TFAC about rack/cable options. OrderIT 167106 filed to run a 10Gbit fiber connection to vlan 265 to a shelf in Forsythe. UIT is on commencement freeze, so work won't occur for at least a week.

**Comment by atz** [comment]
Is this "snowball" delivery approach a satisfactory solution to our `>10GB` file delivery?  Seems like it would be optimal for large file transfer.

**Comment by atz** [comment]
`>10GB` is solved conventionally.  Looking at snowball stuff now.  Using the [Snowball S3 adapter](https://docs.aws.amazon.com/snowball/latest/ug/using-adapter.html) is problematic.  It is a Java application that the docs suggest you are running on a workstation.  That guarantees bottleneck... and we don't have proper workstations located nearby our data (in network terms).  A laptop pulling data from VPN and pushing back to snowball on the same VPN sound like a bad idea.

We could run it on a VM, but we'd be effectively building a puppet VM just for that purpose, or making a one-off for an otherwise important operation.

**Comment by atz** [comment]
We have demonstrated consistent high throughput w/ our async jobs, so I think we don't need anything extra (code-wise or snowball-wise) to attack the backlog.

**Comment by jmartin-sul** [comment]
now that we've ruled out snowball, and we've got some queries for triggering backlog replication manually in chunks (#820), should we close this?

**Comment by SaravShah** [comment]
yup closing , ops concerns now.
