### ISSUE TITLE
Query returning backlog of what needs to be replicated (druid, version, endpoint)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#907]
e.g. we may have replicated druid X version 3, but we need to do versions 1 and 2

Or we added an endpoint and we need to replicate some older versions to the endpoint ....

**Comment by atz** [comment]
For a given version we have `ZipEndpoint.which_need_archive_copy(druid, version)` which answers part of this question.  `PreservedCopy#create_zipped_moab_versions!` calls that while iterating over expected versions, so the problem is effectively solved.  But in the future that could be consolidated to be more efficient (one query).
