### ISSUE TITLE
(PO2R) for each PO, does it have complete_moab and all the zipped_moab_versions with status ok (blocked by #1008 C2A)

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#920]
- for each preserved_object in the catalog, does it have an online PC with status Ok and  does it have all of the archival pres_copies with status ok, per preservation_policy.
    -  this will be a db query - the same as or similar to that used in current replication

**Comment by SaravShah** [comment]
discussed in story time (https://docs.google.com/document/d/10HMhTMWlZaM1DJChFr2r3coOVDZKe0EDAH8PPumb-2E/edit#heading=h.67jvdjt99u6g)

**Comment by SaravShah** [comment]
builds off of #813

**Comment by SaravShah** [comment]
Stub for this method is in #813 -> `PreservedObject.check_endpoints!`
This builds off of #917, active record queries.

**Comment by jmartin-sul** [comment]
can we leverage M2C or one of the existing scheduled audit checks as a framework for running this?  is it possible that PO2R is just grafting C2A onto M2C or C2M?  or is it its own separately schedule process?

we feel this is analogous to the question earlier in development of whether M2C and seeding were the same task (we initially thought they were, but it turned out they were easier to treat as separate tasks).

**Comment by atz** [comment]
Yeah, I'm not sure that repeating our previous pattern is the best strategy.  This seems to me to be about:
1. defining a query or queries to find things that don't match (the hard part being making sure that all N parts are present, when parts_count is a field on the table of parts)
2. *maybe* doing something as a result, but probably not a lot, because our regularly scheduled stuff would be expected to make things eventually consistent.
